if(DEFINED Cairo_ROOT)
  set(CAIRO_INCLUDE_DIR_SEARCH_PATHS ${Cairo_ROOT}/include ${CAIRO_INCLUDE_DIR_SEARCH_PATHS})
	set(CAIRO_LIB_SEARCH_PATHS ${Cairo_ROOT}/lib ${CAIRO_LIB_SEARCH_PATHS})
endif()

# -lcairo
FIND_PATH(CAIRO_INCLUDE_DIR cairo/cairo-gl.h PATHS ${CAIRO_INCLUDE_DIR_SEARCH_PATHS} NO_CMAKE_SYSTEM_PATH)
FIND_LIBRARY(CAIRO_LIBRARIES NAMES cairo libcairo PATHS ${CAIRO_LIB_SEARCH_PATHS} NO_CMAKE_SYSTEM_PATH)


IF(CAIRO_INCLUDE_DIR AND CAIRO_LIBRARIES)
	SET(CAIRO_FOUND TRUE)
  SET(CAIRO_INCLUDE_DIRS ${CAIRO_INCLUDE_DIR} "${CAIRO_INCLUDE_DIR}/cairo")
ENDIF(CAIRO_INCLUDE_DIR AND CAIRO_LIBRARIES)

IF(CAIRO_FOUND)
	IF (NOT LibCairo_FIND_QUIETLY)
		MESSAGE(STATUS "Found cairo-gl includes:	${CAIRO_INCLUDE_DIR}/cairo/cairo_gl.h")
		MESSAGE(STATUS "Found cairo library: ${CAIRO_LIBRARIES}")
	ENDIF (NOT LibCairo_FIND_QUIETLY)
ELSE(CAIRO_FOUND)
	IF (LibCairo_FIND_REQUIRED)
		MESSAGE(FATAL_ERROR "Could NOT find libcairo development files: ${CAIRO_INCLUDE_DIR} :: ${CAIRO_LIBRARIES}")
	ENDIF (LibCairo_FIND_REQUIRED)
ENDIF(CAIRO_FOUND)
